# Generated by Django 3.2.16 on 2023-04-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='Описание'),
        ),
    ]
